export const stateData = {
  sp: { name: "São Paulo", costIndex: 100 },
  rj: { name: "Rio de Janeiro", costIndex: 95 },
  df: { name: "Distrito Federal", costIndex: 90 },
  mg: { name: "Minas Gerais", costIndex: 75 },
  rs: { name: "Rio Grande do Sul", costIndex: 80 },
  pr: { name: "Paraná", costIndex: 80 },
  sc: { name: "Santa Catarina", costIndex: 85 },
  ba: { name: "Bahia", costIndex: 70 },
  pe: { name: "Pernambuco", costIndex: 65 },
  ce: { name: "Ceará", costIndex: 60 },
  go: { name: "Goiás", costIndex: 65 },
  es: { name: "Espírito Santo", costIndex: 75 },
  mt: { name: "Mato Grosso", costIndex: 70 },
  ms: { name: "Mato Grosso do Sul", costIndex: 70 },
  pa: { name: "Pará", costIndex: 55 },
  am: { name: "Amazonas", costIndex: 60 },
  ma: { name: "Maranhão", costIndex: 50 },
  pi: { name: "Piauí", costIndex: 45 },
  al: { name: "Alagoas", costIndex: 50 },
  se: { name: "Sergipe", costIndex: 55 },
  pb: { name: "Paraíba", costIndex: 50 },
  rn: { name: "Rio Grande do Norte", costIndex: 55 },
  ac: { name: "Acre", costIndex: 60 },
  ro: { name: "Rondônia", costIndex: 60 },
  rr: { name: "Roraima", costIndex: 65 },
  ap: { name: "Amapá", costIndex: 65 },
  to: { name: "Tocantins", costIndex: 55 },
};

export type StateKey = keyof typeof stateData;
