name = "freelaz-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "freelaz-api"

[env.staging]
name = "freelaz-api-staging"

# D1 Database configuration (will be created later)
# [[d1_databases]]
# binding = "DB"
# database_name = "freelaz"
# database_id = "your-database-id"

# KV namespace for location caching
[[kv_namespaces]]
binding = "LOCATION_CACHE"
id = "296d1166a9a343978919ff9a44efafa7"
preview_id = "296d1166a9a343978919ff9a44efafa7"

# Environment variables
[vars]
ENVIRONMENT = "development"

# KV namespace for caching (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id" 