name = "freelaz-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "freelaz-api"

[env.staging]
name = "freelaz-api-staging"

# D1 Database configuration (will be created later)
# [[d1_databases]]
# binding = "DB"
# database_name = "freelaz"
# database_id = "your-database-id"

# Environment variables
[vars]
ENVIRONMENT = "development"

# KV namespace for caching (optional)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id" 